### PR TITLE
Search functionality logic implementation

### PR DESCRIPTION
**Pull request by jainammshah12**

### CODE REVIEW

**Review by huy2272 — CHANGES_REQUESTED** [review]
Hi Jainam, I don't see any functional logic implementation in this PR. Can you double check?
The only change I can see is you changing `ObjectId` to `String`
image

**Comment by jainammshah12** [comment]
I don't know why I am not able to do it, but I think it is good enough. I talked to Hawa, she is fine with the current parameters. I implemented the logic but it didn't show for some reason.

**Comment by asu21244** [comment]
> I don't know why I am not able to do it, but I think it is good enough. I talked to Hawa, she is fine with the current parameters. I implemented the logic but it didn't show for some reason.



> I don't know why I am not able to do it, but I think it is good enough. I talked to Hawa, she is fine with the current parameters. I implemented the logic but it didn't show for some reason.

Can you explain why u used @RequestParam instead of @RequestBody?

**Comment by huy2272** [comment]
@asu21244 Is the search functionality working for you? How can it be good enough if the logic isn't there?

**Comment by asu21244** [comment]
> @asu21244 Is the search functionality working for you? How can it be good enough if the logic isn't there?

It's not working at all

**Comment by jainammshah12** [comment]
Okay, I have added search functionality logic on the backend again.. should I commit again? Or @asu21244 will you be fine? Also let me know if postman starts working..

**Comment by asu21244** [comment]
I mean yes cause POST still isn't working and I don't know why.
Screenshot 2023-11-29 171154

**Pull request closed without merging**
